options:
	pe: §7[§4§lERROR§7] §8» §c
	p: §7[§9DD§7] §8» §3
	pc: §6
	c1: §3
	c2: §b

command /respekt <offlineplayer>:
	trigger:
		if arg-1 is online:
			send "{@pc}%player% {@c1}schenkt {@pc}%arg-1% {@c1}eine Runde Respekt." to all players
			send "" to all players
			send "§d§l███" to all players
			send "§d§l█" to all players
			send "§d§l██" to all players
			send "§d§l█" to all players
			send "§d§l█" to all players
		else:
			send "{@pe}Dieser Spieler ist nicht online!"